### ISSUE TITLE
Using triggers search for fine-tuned model

### ISSUE THREAD

**Issue by AnnaSou** [ewsheng/controllable-nlg-biases#2]
Hello @ewsheng ,

I am trying to search for triggers in my fine-tuned GPT2. 
So, I changed the model to:
`model = GPT2LMHeadModel.from_pretrained(params.model_name_or_path)
`
But getting the following error:
```
Traceback (most recent call last):
  File "src/create_adv_token.py", line 839, in <module>
    run_model()
  File "src/create_adv_token.py", line 667, in run_model
    extracted_grad = extracted_grads[i]
IndexError: list index out of range
```
Any idea how to fix it would be extremely appreciated!

Thanks,
Anna

**Comment by ewsheng** [comment]
This is probably because there wasn't a `params.model_name_or_path` parameter; I've updated the code to include this and a few other params in the latest commit 3214c7a, and you should now be able to use a fine-tuned model.

**Comment by AnnaSou** [comment]
@ewsheng  Thank you for the reply. I have tried and now getting this error:
Traceback (most recent call last):
```
  File "src/create_adv_token.py", line 831, in <module>
    run_model()
  File "src/create_adv_token.py", line 289, in run_model
    params.tokenizer_name if params.tokenizer_name else params.model_name_or_path)
  File "/fs/clip-scratch/annasout/miniconda3/envs/triggers/lib/python3.6/site-packages/transformers/tokenization_auto.py", line 197, in from_pretrained
    return tokenizer_class_py.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/fs/clip-scratch/annasout/miniconda3/envs/triggers/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 393, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/fs/clip-scratch/annasout/miniconda3/envs/triggers/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 544, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/fs/clip-scratch/annasout/miniconda3/envs/triggers/lib/python3.6/site-packages/transformers/tokenization_gpt2.py", line 149, in __init__
    super().__init__(bos_token=bos_token, eos_token=eos_token, unk_token=unk_token, **kwargs)
  File "/fs/clip-scratch/annasout/miniconda3/envs/triggers/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 337, in __init__
    assert isinstance(value, str)
AssertionError

```

Any advice would be appreciated!

Thanks,
Anna

**Comment by ewsheng** [comment]
If you're using a fine-tuned model, have you either set `tokenizer_name` to the name of a predefined tokenizer (e.g., `gpt2`) or to a directory containing vocabulary files required by the tokenizer (more info: https://huggingface.co/transformers/internal/tokenization_utils.html#transformers.tokenization_utils_base.PreTrainedTokenizerBase.from_pretrained)?

**Comment by AnnaSou** [comment]
I did try both - I am using fine-tuned gpt2: so - just keeping gpt2 or having my directory. Still getting the same message:
```
Traceback (most recent call last):
  File "src/create_adv_token.py", line 831, in <module>
    run_model()
  File "src/create_adv_token.py", line 289, in run_model
    params.tokenizer_name if params.tokenizer_name else params.model_name_or_path)
  File "/fs/clip-scratch/annasout/miniconda3/envs/triggers/lib/python3.6/site-packages/transformers/tokenization_auto.py", line 197, in from_pretrained
    return tokenizer_class_py.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/fs/clip-scratch/annasout/miniconda3/envs/triggers/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 393, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/fs/clip-scratch/annasout/miniconda3/envs/triggers/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 544, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/fs/clip-scratch/annasout/miniconda3/envs/triggers/lib/python3.6/site-packages/transformers/tokenization_gpt2.py", line 149, in __init__
    super().__init__(bos_token=bos_token, eos_token=eos_token, unk_token=unk_token, **kwargs)
  File "/fs/clip-scratch/annasout/miniconda3/envs/triggers/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 337, in __init__
    assert isinstance(value, str)
AssertionError

```

Thanks,
Anna

**Comment by ewsheng** [comment]
I'm not sure why you're getting this error (setting the `tokenizer_name` to `gpt2` seems to be working for me). Maybe try replacing https://github.com/ewsheng/controllable-nlg-biases/blob/master/src/create_adv_token.py#L288 with `tokenizer = GPT2Tokenizer.from_pretrained('gpt2')` (and import `GPT2Tokenizer`)?

**Comment by AnnaSou** [comment]
I am getting this error: 
```
Traceback (most recent call last):
  File "src/create_adv_token.py", line 830, in <module>
    run_model()
  File "src/create_adv_token.py", line 660, in run_model
    extracted_grad = extracted_grads[i]
IndexError: list index out of range
srun: error: clipgpu02: task 0: Exited with exit code 1
```

May it be because in my case gpt2 finetuned on snli corpus?

Thanks!

**Comment by AnnaSou** [comment]
It seems that I managed to fix the problem. Once again, thanks for the help!

**Comment by AnnaSou** [comment]
Hello @ewsheng ! 
My change did not work. So, I have a model finetuned on SNLI data with EOS, BOS, and 3 special tokens.
Here is how the changed tokenizer looks like:
```
model = AutoModelWithLMHead.from_pretrained(params.model_name_or_path)
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
special_tokens_dict = {'bos_token': '<BOS>', 'eos_token': '<EOS>','additional_special_tokens': ['<premise>','<label>','<hypo>']}
num_added_toks = tokenizer.add_special_tokens(special_tokens_dict)
model.resize_token_embeddings(len(tokenizer))
model.eval()
model.to(device)
```
and here is the error I am getting:
```
Traceback (most recent call last):
  File "src/create_adv_token.py", line 834, in <module>
    run_model()
  File "src/create_adv_token.py", line 664, in run_model
    extracted_grad = extracted_grads[i]
IndexError: list index out of range
srun: error: clipgpu02: task 0: Exited with exit code 1
```
If you have any ideas on how to fix that or what to test, I would extremely appreciate this!
Thanks,
Anna

**Comment by ewsheng** [comment]
So the error is at least partly because the hooks weren't being properly applied, because the hooks depended on a hardcoded vocab size, and adding your `special_tokens_dict` changes the vocab size. I've updated the code to rely on the size of the tokenizer in 2f6d38b instead--hopefully that fixes your issue!

**Comment by AnnaSou** [comment]
Now it works! thank you for the help!
